functionsDirectory = "C:\\Users\\migue\\Documents\\Proyectos antigravity\\Falla Turia\\netlify\\functions"
functionsDirectoryOrigin = "default"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "C:\\Users\\migue\\Documents\\Proyectos antigravity\\Falla Turia\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Users\\migue\\Documents\\Proyectos antigravity\\Falla Turia\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]
included_files = ["node_modules/pdf-parse/**"]

[[redirects]]
from = "/api/webhook-register"
to = "https://n8n.i-automate.es/webhook/a75d7fa4-6bb4-4691-88ca-01850bb41add"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/webhook-register"
to = "https://n8n.i-automate.es/webhook/a75d7fa4-6bb4-4691-88ca-01850bb41add"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]
X-From = "Netlify"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]